include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - avoid_print
    - unnecessary_null_in_if_null_operators
    - prefer_typing_uninitialized_variables
    - no_leading_underscores_for_local_identifiers
    - use_build_context_synchronously
    - avoid_unnecessary_containers
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_returning_null_for_void
    - prefer_relative_imports